[NbConvertApp] Converting notebook dm_butler_skymap.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: lsst
[NbConvertApp] ERROR | Error while converting 'dm_butler_skymap.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import glob
import warnings
import sqlite3
import re

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.path import Path
import matplotlib.patches as patches
%matplotlib inline

import lsst.afw.geom as afw_geom
import lsst.afw.cameraGeom as cameraGeom
import lsst.daf.persistence as dp
# The lsst_sims code issues some ignorable warnings regarding ids used for querying the object
# databases.
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    import lsst.sims.coordUtils
    from lsst.sims.catUtils.utils import ObservationMetaDataGenerator
    from lsst.sims.utils import getRotSkyPos
    
from desc_dc2_dm_data import REPOS
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-7384f3feb142>[0m in [0;36m<module>[0;34m[0m
[1;32m     18[0m [0;32mwith[0m [0mwarnings[0m[0;34m.[0m[0mcatch_warnings[0m[0;34m([0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     19[0m     [0mwarnings[0m[0;34m.[0m[0msimplefilter[0m[0;34m([0m[0;34m"ignore"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 20[0;31m     [0;32mimport[0m [0mlsst[0m[0;34m.[0m[0msims[0m[0;34m.[0m[0mcoordUtils[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     21[0m     [0;32mfrom[0m [0mlsst[0m[0;34m.[0m[0msims[0m[0;34m.[0m[0mcatUtils[0m[0;34m.[0m[0mutils[0m [0;32mimport[0m [0mObservationMetaDataGenerator[0m[0;34m[0m[0;34m[0m[0m
[1;32m     22[0m     [0;32mfrom[0m [0mlsst[0m[0;34m.[0m[0msims[0m[0;34m.[0m[0mutils[0m [0;32mimport[0m [0mgetRotSkyPos[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'lsst.sims'
ModuleNotFoundError: No module named 'lsst.sims'

